### ISSUE TITLE
Can you add the Topic Combos into the Wiki?

### ISSUE THREAD

**Issue by PaddedGamer** [BasvanE/GDT-Expansion-Pack#1]
So Some of the topics are brain dead confusing for what is a awesome combo. Like Caveman.....I Don't even began to know what to combine that with. Or Maze Adventurer is okay and Sim was Good? Wtf is the perfect combo right there? 
I mean you gave all the topics Great combos right? Or is there only good combos for some of them cause I'm confused and I really think there should be a wiki page for Great Combos I'm somewhat confused.

**Comment by BasvanE** [comment]
Well, that could be possible. But it would be a pain in the **\* to do so. Since there are 80 new topics and they have 9 attributes each. Maybe I can do it steps but it will take some time to finish it.

**Comment by PaddedGamer** [comment]
@DzjengisKhan Thank you so much I hope you make the wiki Page. I know it's not going to be the easiest thing in the world but thank you for listening to me and I hope you make the wiki page that will help a ton.

**Comment by LineLiar** [comment]
It would be somewhat a bit cheaty. ;) That's no fun! If anyone would take the time to do this though, I'm perfectly fine with adding it. I think it's not needed and I'm (and DzjengisKhan) am/are not gonna make it. Feel free to submit a list yourself for the wiki.
