### ISSUE TITLE
Difficulty Option

### ISSUE THREAD

**Issue by SadPandaFace** [BasvanE/GDT-Expansion-Pack#14]
For some reason, I cannot seem to be able to select the difficulty of the game. I've tried looking in the settings, though I assume it's supposed to appear when I start a new game, however, it doesn't. Everything else in the mod has been working just fine for me, except this feature. I'd like to know how to fix this, please

**Comment by BasvanE** [comment]
When you start a new game, click on the gear at the right, the window will extend with the new option (along with some other standard things)

**Comment by SadPandaFace** [comment]
The only thing I see when I click on the little gear is the game length option.
