### ISSUE TITLE
Uncaught error (game.gameSize)

### ISSUE THREAD

**Issue by Efreak** [BasvanE/GDT-Expansion-Pack#2]
Background: I'm running with the following mods: GDT-Expansion-Pack, CheatMod, and the official cheat API enabled. So far as I can tell, expansion & cheatmod have nothing in common, and I can't seem to deselect the API without deselecting everything else.

Problem: When I finished the first game, the below error occurred. I ignored it and moved on. It happened after the second, etc games too, and was successfully ignored. However, whenever I try to click on my character to do a game report, it pops up the error again--and then doesn't pop up the menu, which means I can't proceed.

```
Uncaught error. Please report this to support@greenheartgames.com: 
Uncaught TypeError: Cannot read property 'gameSize' of null
(file:///F:/Program%20Files%20(x86)/Steam/steamapps/common/Game%20Dev%20Tycoon/mods/ExpansionPack/source/source.js:1354)

Please restart the game.
```

The file/section in question is [source.js:1349]([source.js:1349](https://github.com/DzjengisKhan/GDT-Expansion-Pack/blob/master/ExpansionPack/source/source.js#L1349):
`var game = GameManager.company.currentGame;`

Yes, it says to report to their support, however the error is in your script. Annoyingly, the dialog box from GDT is too small to see the whole error text, and doesn't scroll, resize, or allow selection; I had to search the memory using process explorer to get the full string.

**Comment by BasvanE** [comment]
Hello Efreak, Thank you for reporting it to me, I've heard it from several people but the odd thing is that it doen'st happen on my end. I've took a look and I think i now know what caused the problem and i believe its fixed now. Could you download the new version and see if you still get the error??

**Comment by Efreak** [comment]
Tested a brand new game. I am now unable to skip or proceed with the tutorial. It appears that the issue at fault here is actually something on their end, as there is no error that contains \mods\ now. Either that or there's something wrong with their traces. I've got the relevant searches for 'Uncaught Error' from all 3 GDT processes [here](https://gist.github.com/Efreak/ad0d66dfd82864def499), though I doubt they'll help. I'm trying it without cheatmod now.

**Comment by Efreak** [comment]
I've removed Cheatmod and it works perfectly. Apparently I've been complaining to the wrong place; I assumed that cheatmod was bug-free as nobody else was reporting any issues with it. Either that or there is indeed something wrong with using both at the same time.

**Comment by Unbegier** [comment]
Some error. Using GDT-Expansion-Pack and Platform Randomiser.

**Comment by LineLiar** [comment]
Do you have the latest version? If not, update to the latest version. (Make sure to make a new save file because it added a console.)

If you have the latest version then restart the game. I had this once, restarted the game and then it never happened to me again! ;p
