### ISSUE TITLE
Mod Not showing up in the mods Button

### ISSUE THREAD

**Issue by Doomofyou** [BasvanE/GDT-Expansion-Pack#5]
I got it GDT working to get the mods, But The expansion pack mod isn't showing up on the list.

Edit:  I've worked it out, But I can't get it to work. Like it says to restart. I restart it, no changes and a whole bunch of error messages.

**Comment by BasvanE** [comment]
What error messages do you get?

**Comment by Doomofyou** [comment]
Error:
Could not Load one of the scripts C:\Program Files(x86)\Steam\steamapps\common\Game Dev Tycoon\Mods\odt-modAPI/helpers/check.is.C:\Program files...

If there is any more than that, it cuts off half way through the line starting at 'Tycoon'

And also, I get many of them as soon as I close them.

**Comment by LTLightning** [comment]
I had this problem, but I got it fixed somehow. I think it has to do something with the filepath.
Is your mod path: Game Dev Tycoon/mods/Expansion Pack/(the code)

**Comment by Doomofyou** [comment]
So... I Should change it? and to what?

**Comment by LineLiar** [comment]
Do you have ExpansionPack-master in the Mods folder or ExpansionPack? You always should have the map in the Mods folder where the license and package.json is in. ;)

**Comment by Doomofyou** [comment]
Map?

**Comment by BasvanE** [comment]
He meant folder, your directory should be: game dev tycoon/mods/ExpansionPack/package.json

**Comment by Doomofyou** [comment]
Got it to work. Thank you so much. But don't forget to Mention me. After all, I helped you Develop the original Mod. This is DmooUmoo.
