### ISSUE TITLE
In All Situations, Any Game Created Results in 0 Sales

### ISSUE THREAD

**Issue by RedMageKnight** [BasvanE/GDT-Expansion-Pack#6]
After installing this mod and tinkering around with it, it seems that whenever I create any game, I get the ratings and reviews, but then the message that comes up when your game is removed from the market occurs. It results in 0 sales and 0 units sold. I don't know if this is a result of a recent update or not. I am using the beta version of the game, but I had the same issues with the normal version.

**Comment by LTLightning** [comment]
I have this same problem too.

**Comment by BasvanE** [comment]
If you had the same issue when you used the normal version, the error isn't caused by my mod. I'm sorry but i can't help you any further with your problem

**Comment by RedMageKnight** [comment]
How? There are no other mods installed but yours. When I say I ran it in normal mode I meant not beta with your mod installed. I don't have this problem when I remove your mod.

**Comment by RedMageKnight** [comment]
Please reopen this issue as it seems at least one other person is having this same issue.
