### ISSUE TITLE
Bug / Fix: 0 Units sales on Game release.

### ISSUE THREAD

**Issue by Alucard87** [BasvanE/GDT-Expansion-Pack#7]
Hey,
i got the same Problem like RedMageKnight that when i had installed your Mod ( followed exaclty the instructions and it was the first and only mod i installed) any Game of me directly got sold out with 0 units.

I tried a few things and might found a solution (what probably help you fixing this issue).

It seems to happen only on first / clean install of your Mod.
You just need to set once a custom price and after this (even if you stay at 7) its "fixed" for every game you begin.

For RedMageKnight, to set custom price, just click while game developing and open the menu for"custom price".

Please refer if this helped you too.

**Comment by LTLightning** [comment]
This fixed the problem! Thanks! :D

**Comment by RedMageKnight** [comment]
Ah, this did the trick! This was very helpful, I wish I would have seen this sooner, thank you :) :+1:
