### ISSUE TITLE
Games arent selling

### ISSUE THREAD

**Issue by Zetton101** [BasvanE/GDT-Expansion-Pack#8]
As soon as I release a game it says its been taken off the market the next week without selling a single copy. Help?

**Comment by BasvanE** [comment]
Check the notes on the greenheart games forum topic. ^^

**Comment by RedMageKnight** [comment]
Hey Zetton101, I had this same issue before - check the closed issues list, and under the first one, there's a post in there by a user named Alucard87. He found a solution to this problem that you are most likely similarly having. Give it a shot.

Edit: Here's a link: https://github.com/DzjengisKhan/GDT-Expansion-Pack/issues/7
